// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        *int   `json:"id"`
	UserID    int    `json:"userId"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type CreateEventResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    *Event `json:"data"`
}

type CreateUserResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    *User  `json:"data"`
}

type DeleteUserResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Event struct {
	ID          *int   `json:"id"`
	Name        string `json:"name"`
	Username    string `json:"username"`
	Host        string `json:"host"`
	Description string `json:"description"`
	Datetime    string `json:"datetime"`
	Location    string `json:"location"`
	Category    string `json:"category"`
	Photo       string `json:"photo"`
}

type GetUserResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    *User  `json:"data"`
}

type GetUsersResponse struct {
	Code    int     `json:"code"`
	Message string  `json:"message"`
	Data    []*User `json:"data"`
}

type Login struct {
	ID    *int    `json:"id"`
	Name  *string `json:"name"`
	Token string  `json:"token"`
}

type NewEvent struct {
	Name     string `json:"name"`
	Host     string `json:"host"`
	Datetime string `json:"datetime"`
	Location string `json:"location"`
	Category string `json:"category"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Participant struct {
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}

type SuccessResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type UpdateEvent struct {
	Name        *string `json:"name"`
	Host        *string `json:"host"`
	Description *string `json:"description"`
	Datetime    *string `json:"datetime"`
	Location    *string `json:"location"`
	Category    *string `json:"category"`
	Photo       *string `json:"photo"`
}

type UpdateEventResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    *Event `json:"data"`
}

type UpdateUser struct {
	Name     *string `json:"name"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
	Phone    *string `json:"phone"`
	Avatar   *string `json:"avatar"`
}

type UpdateUserResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    *User  `json:"data"`
}

type User struct {
	ID       *int    `json:"id"`
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Phone    *string `json:"phone"`
	Avatar   *string `json:"avatar"`
}

type AuthLoginResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    *Login `json:"data"`
}

type EventResponse struct {
	Event     []*Event `json:"event"`
	TotalPage int      `json:"totalPage"`
}
