// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginResponse struct {
	Message string `json:"message"`
	ID      int    `json:"id"`
	Name    string `json:"name"`
	Email   string `json:"email"`
	Token   string `json:"token"`
}

type Message struct {
	Message string `json:"message"`
}

type NewUser struct {
	Name         string  `json:"name"`
	Email        string  `json:"email"`
	Password     string  `json:"password"`
	Organization *string `json:"organization"`
	PhoneNumber  *string `json:"phoneNumber"`
	Avatar       *string `json:"avatar"`
}

type UpdateUser struct {
	Name         *string `json:"name"`
	Email        *string `json:"email"`
	Password     *string `json:"password"`
	Organization *string `json:"organization"`
	PhoneNumber  *string `json:"phoneNumber"`
	Avatar       *string `json:"avatar"`
}

type User struct {
	ID           *int    `json:"id"`
	Name         string  `json:"name"`
	Email        string  `json:"email"`
	Password     string  `json:"password"`
	Organization *string `json:"organization"`
	PhoneNumber  *string `json:"phoneNumber"`
	Avatar       *string `json:"avatar"`
}
